sudo: false

language: generic

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=spy-crowd
    - CLUSTER_NAME_PRD=europe-cluster
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-b
    - DOCKER_IMAGE_NAME=dgraph-api
    - KUBE_DEPLOYMENT_NAME=dgraph-api
    - KUBE_DEPLOYMENT_CONTAINER_NAME=dgraph-api

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./update-service.sh v0.9.6.9
    skip_cleanup: true
    on:
      branch: master
